### PR TITLE
sort results of ls command

### PR DESCRIPTION
**Pull request by fJancsoSzabo**
I don't know of any reason you *wouldn't* want these sorted?

### CODE REVIEW

**Comment by fJancsoSzabo** [comment]
I honestly just got tired of constantly `| sort`'ing the results and figured I'd open a PR.

Based on the Java client library, it seems like zookeeper makes no guarantees about the ordering of the results: https://zookeeper.apache.org/doc/r3.3.3/api/org/apache/zookeeper/ZooKeeper.html#getChildren(java.lang.String,%20boolean)

**Comment by shlomi-noach** [comment]
All right. I guess for huge recurring queries this might incur some
performance penalty. How do you feel about adding a Boolean command like
flag to execute sorting?

**Comment by fJancsoSzabo** [comment]
I honestly don't know enough about the usual sizes of zookeeper stores to know whether the performance hit will be noticeable.  I wrote a quick benchmark to test things out, and it tick up above 0.1s/op when I had 300k entries in the slice, which makes me think it could be reasonable to make the default action to sort the results?

I'll defer to you on the decision here.

[sort_test.txt](https://github.com/outbrain/zookeepercli/files/2084869/sort_test.txt)

**Output:**
```
goos: darwin
goarch: amd64
pkg: github.com/fJancsoSzabo/sortbenches
BenchmarkFoo-8   	      10	 137649754 ns/op
PASS
ok  	github.com/fJancsoSzabo/sortbenches	13.663s
```

**Comment by fJancsoSzabo** [comment]
Actually, something I just noticed.  [Here](https://github.com/outbrain/zookeepercli/blob/master/zk/zk.go#L176) in `lsr` the results are already sorted.  Given that, I don't think it would be an issue to sort `ls` output too.

**Comment by shlomi-noach** [comment]
> Actually, something I just noticed. Here in lsr the results are already sorted. 

Oh that's right. OK, sure, given that ZK itself just doesn't make any guarantee on result order, any order is as good as any; let's proceed with just sorting the results.

**Pull request merged**
