### PR TITLE
multithreaded lsr

### LINKED ISSUE #34: allow multithreading for lsr
`lsr` is **incredibly** slow with large zookeeper instances when running it from the root.  I ran some benchmarks and it seems like the majority of the time is spent waiting due to network latency.

It should be possible to increase the speed of this by allowing multiple goroutines to query zookeeper.  I'm thinking of adding two flags `--parallelize` and `--numgoroutines`.  Would there be any interest?

### PR DESCRIPTION
**Pull request by fJancsoSzabo**
Closes #34. Allows you to throw more cpu at the problem, and works beautifully.  It actually lets `lsr` finish for me and it only takes a minute with 20 concurrent requests.

### CODE REVIEW

**Comment by fJancsoSzabo** [comment]
@shlomi-noach there's some things I'd like your input on:
- Can you think of a better flag name?  It feels to verbose for me, but I didn't know what else to call it
- What should this do when it hits an error at one of the nodes?  Currently, it reports it and keeps going, but I wasn't sure what to do if there's *several* errors.  Return a list of them and print them all?

**Comment by fJancsoSzabo** [comment]
I need to patch this a little I just realized, currently it returns the absolute path rather than the relative, which is what the existing implementation does.

**Comment by fJancsoSzabo** [comment]
@shlomi-noach I would greatly appreciate it if you could take a look at this

**Comment by fJancsoSzabo** [comment]
Closing due to lack of interest from maintainers.

**Comment by shlomi-noach** [comment]
Please reopen. There is no lack of interest, there is a huge backlog of
work. Thank you.

**Pull request closed without merging**
